# Inserts a blank line between shell prompts
add_newline = false

[aws]
symbol = " "
disabled = true

[conda]
symbol = " "
disabled = true

[dart]
symbol = " "
disabled = true

[docker_context]
symbol = " "
disabled = true

[elixir]
symbol = " "
disabled = true

[elm]
symbol = " "
disabled = true

## GIT STATUS STUFF
[git_metrics]
disabled = true

[git_status]
disabled = true


[git_branch]
symbol = " "

[golang]
symbol = " "
disabled = true

[hg_branch]
symbol = " "

[java]
symbol = " "
disabled = true

[julia]
symbol = " "
disabled = true

[nim]
symbol = " "
disabled = true

[nix_shell]
symbol = " "
disabled = true

[nodejs]
symbol = " "
disabled = true

[package]
symbol = " "
disabled = true

[perl]
symbol = " "
disabled = true

[php]
symbol = " "
disabled = true

[python]
symbol = " "
disabled = true

[ruby]
symbol = " "
disabled = true

[rust]
symbol = " "
disabled = true

[swift]
symbol = "ﯣ "
disabled = true
